[package]
name = "bot-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtts = "0.1.0"
rodio = "0.14.0"
rand = "0.8.0"
random_choice = "0.3.2"